AllCops:
  NewCops: enable
  TargetRubyVersion: '3.4'
  Exclude:
    - vendor/**/*
    - bin/**/*

Style:
  Enabled: false

Metrics:
  Enabled: false

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec
